{% set version = "8.0.3" %}

package:
  name: dydxprotocol-v4-proto-js-split
  version: {{ version }}

source:
  url: https://github.com/dydxprotocol/v4-chain/archive/refs/tags/protocol/v{{ version }}.tar.gz
  sha256: 2d538f62f2580bccf6609b7da94f4986828a7cde2967e51fd3ab080b477542ee
  folder: js_module_source

build:
  # wimdows needs docker in experimental mode
  skip: true  # [win]
  number: 0

requirements:
  build:
    - buf
    - docker  # [win]
    - make
    - nodejs >=18
  host:
    - bash  # [unix]
    - nodejs >=18
    - pnpm
    - pnpm-licenses
  run:
    - nodejs >=18

outputs:
  - name: dydxprotocol-v4-proto-js
    script: helpers/install-js.sh  # [unix]
    script: helpers\\install-js.bat  # [win]
    requirements:
      host:
        - nodejs >=18
      run:
        - nodejs >=18
    test:
      commands:
        - test -d $PREFIX/lib/node_modules/@dydxprotocol/v4-proto  # [unix]
        - if not exist %PREFIX%\\lib\\node_modules\\@dydxprotocol\\v4-proto exit 1  # [win]

  # - Naming conversion
  - name: dydxprotocol_v4_proto_js
    requirements:
      run:
        - {{ pin_subpackage('dydxprotocol-v4-proto-js', exact=True) }}
    test:
      commands:
        - test -d $PREFIX/lib/node_modules/@dydxprotocol/v4-proto  # [unix]
        - if not exist %PREFIX%\\lib\\node_modules\\@dydxprotocol\\v4-proto exit /b 1  # [win]

about:
  home: https://github.com/dydxprotocol/v4-chain
  summary: 'The dYdX v4 software (the ”dYdX Chain”) is a sovereign blockchain software built using Cosmos SDK and CometBFT.'
  description: |
    The dYdX v4 software (the ”dYdX Chain”) is a sovereign blockchain software built using
    Cosmos SDK and CometBFT. It powers a robust decentralized perpetual futures exchange
    with a high-performance orderbook and matching engine for a feature-rich, self-custodial
    perpetual trading experience on any market.
  license: AGPL-3.0-only
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt

extra:
  recipe-maintainers:
    - MementoRC
  feedstock-name: dydxprotocol-v4-proto-js
